DROP TABLE dog;

CREATE TABLE dog (
	num		NUMBER			CONSTRAINT DOG_NUM_PK PRIMARY KEY,
	name	VARCHAR2(20)	CONSTRAINT DOG_NAME_NN NOT NULL,
	age		NUMBER(3)		DEFAULT 0
);

INSERT INTO dog
VALUES (1, '»Úµ’¿Ã', 10);

INSERT INTO dog
VALUES (2, '∆ƒ∂˚¿Ã', 8);

INSERT INTO dog
VALUES (3, '±Ùµ’¿Ã', 18);
