CREATE TABLE board(
	boardnum	NUMBER			CONSTRAINT BOARD_BNUM_PK PRIMARY KEY,
	writer		VARCHAR2(20)	CONSTRAINT BOARD_WRITER_NN NOT NULL,
	title		VARCHAR2(50)	CONSTRAINT BOARD_TITLE_NN NOT NULL,
	text		VARCHAR2(1000)	CONSTRAINT BOARD_TEXT_NN NOT NULL,
	hitnum		NUMBER			DEFAULT 0,
	indate		DATE			DEFAULT SYSDATE
);

-- 게시글 시퀀스
CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1;

-- ON DELETE CASCADE: 참조하고 있는 컬럼의 ROW가 지워지면 해당 컬럼도 지워짐.
-- VARCHAR2 타입의 최대길이는 4000바이트라고 한다.
CREATE TABLE reply(
	replynum	NUMBER			CONSTRAINT REPLY_RNUM_PK PRIMARY KEY,
	boardnum	NUMBER			CONSTRAINT REPLY_BNUM_FK REFERENCES board(boardnum) ON DELETE CASCADE,
	writer		VARCHAR2(20)	CONSTRAINT REPLY_WRITER_NN NOT NULL,
	retext		VARCHAR2(1000)	CONSTRAINT REPLY_RETEXT_NN NOT NULL
);

-- 댓글 시퀀스
CREATE SEQUENCE reply_seq
START WITH 1
INCREMENT BY 1;

